title: Mauvois — Portfolio
description: Portfolio Site displaying some of my projects
remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme

# Optional settings
show_downloads: false
google_analytics: UA-XXXXXXXX-X

github:
  owner_url: https://github.com/Mauvois
  repository_url: https://github.com/Mauvois/mauvois.github.io
  zip_url: https://github.com/Mauvois/mauvois.github.io/archive/refs/heads/main.zip
  tar_url: https://github.com/Mauvois/mauvois.github.io/archive/refs/heads/main.tar.gz
  is_project_page: true
  is_user_page: false

