title: Roger MAUVOIS
description: Développeur fullstack — Data MLOps.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

# Optional settings
show_downloads: false
google_analytics: UA-XXXXXXXX-X

github:
  owner_url: https://github.com/Mauvois
  repository_url: https://github.com/Mauvois/mauvois.github.io
  zip_url: https://github.com/Mauvois/mauvois.github.io/archive/refs/heads/main.zip
  tar_url: https://github.com/Mauvois/mauvois.github.io/archive/refs/heads/main.tar.gz
  is_project_page: true
  is_user_page: false