# _config.yml
title: Mauvois — Portfolio
description: Portfolio Site displaying some of my projects
remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme

# Optional settings
show_downloads: false
google_analytics: UA-XXXXXXXX-X
