# _config.yml
title: Your Site Title
description: Your Site Description
remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme

# Optional settings
show_downloads: false
google_analytics: UA-XXXXXXXX-X
